services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ml:/ml
      - ./weights:/weights
      - ./image:/image
      - ./examples:/examples
      - ./mlruns:/mlruns
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - minio
      - mlflow
    shm_size: "4g"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  react:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - django

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb local/models --ignore-existing &&
      mc mb local/images --ignore-existing &&
      mc mb local/results --ignore-existing &&
      mc mb local/mlflow --ignore-existing &&
      mc anonymous set download local/images &&
      mc anonymous set download local/results &&
      echo 'MinIO buckets created: models, images, results, mlflow (images & results are public)'"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_ENABLE_STATIC_FILE_SERVE=true
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio
    command: >
      sh -c "pip install mlflow boto3 &&
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns --default-artifact-root s3://mlflow/ --allowed-hosts 'localhost:*,mlflow:*,django:*,127.0.0.1:*,0.0.0.0:*'"
