services:
  django:
    extends:
      file: docker-compose.yml
      service: django
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
